=== LukasVerwiebe/Internetsprachen-INS/Praktikum-INS/Java-Programm/xml/test.dtd
<!ELEMENT FeedbackDaten (PersoenlicheDaten, Checkboxen, EntdecktDurch, Noten, Verbesserung, Spamschutz)>
<!ATTLIST FeedbackDaten
Uhrzeit CDATA #REQUIRED
Datum CDATA #REQUIRED
>
<!ELEMENT PersoenlicheDaten (Anrede, Vorname, Nachname, Alter, Telefonnummer, Emailadresse, Webseite)>
<!ATTLIST PersoenlicheDaten
position CDATA #REQUIRED
id CDATA #REQUIRED
>
<!ELEMENT Anrede (#PCDATA)>
<!ELEMENT Vorname (#PCDATA)>
<!ELEMENT Nachname (#PCDATA)>
<!ELEMENT Alter (#PCDATA)>
<!ELEMENT Telefonnummer (#PCDATA)>
<!ELEMENT Emailadresse (#PCDATA)>
<!ELEMENT Webseite (#PCDATA)>
<!ELEMENT Checkboxen (Mailbox, Rueckfragen, erneuterBesuch)>
<!ATTLIST Checkboxen
position CDATA #REQUIRED
id CDATA #REQUIRED
>
<!ELEMENT Mailbox (#PCDATA)>
<!ELEMENT Rueckfragen (#PCDATA)>
<!ELEMENT erneuterBesuch (#PCDATA)>
<!ELEMENT EntdecktDurch (AufmerksamDurch)>
<!ATTLIST EntdecktDurch
position CDATA #REQUIRED
id CDATA #REQUIRED
>
<!ELEMENT AufmerksamDurch (#PCDATA)>
<!ELEMENT Noten (NoteInhalt, NoteAussehen)>
<!ATTLIST Noten
position CDATA #REQUIRED
id CDATA #REQUIRED
>
<!ELEMENT NoteInhalt (#PCDATA)>
<!ELEMENT NoteAussehen (#PCDATA)>
<!ELEMENT Verbesserung (Vorschlag)>
<!ATTLIST Verbesserung
position CDATA #REQUIRED
id CDATA #REQUIRED
>
<!ELEMENT Vorschlag (#PCDATA)>
<!ELEMENT Spamschutz (Passwort)>
<!ATTLIST Spamschutz
position CDATA #REQUIRED
id CDATA #REQUIRED
>
<!ELEMENT Passwort (#PCDATA)>

=== LukasVerwiebe/Internetsprachen-INS/Praktikum-INS/03.01.2022_07_30_26.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FeedbackDaten SYSTEM "test.dtd"><FeedbackDaten Datum="03.01.2022" Uhrzeit="07:30:26"><PersoenlicheDaten id="1" position="test"><Anrede>Herr</Anrede><Vorname>Lukas</Vorname><Nachname>ver</Nachname><Alter>21</Alter><Telefonnummer>344566</Telefonnummer><Emailadresse>test@web.de</Emailadresse><Webseite>tedzWebseite</Webseite></PersoenlicheDaten><Checkboxen id="2" position="test2"><Mailbox>ausgewÃ¤hlt</Mailbox><Rueckfragen>zur VerfÃ¼gung</Rueckfragen><erneuterBesuch>Ja</erneuterBesuch></Checkboxen><EntdecktDurch id="3" position="test3"><AufmerksamDurch>Freunde/Bekannte</AufmerksamDurch></EntdecktDurch><Noten id="4" position="test4"><NoteInhalt>3</NoteInhalt><NoteAussehen>2</NoteAussehen></Noten><Verbesserung id="5" position="test5"><Vorschlag></Vorschlag></Verbesserung><Spamschutz id="6" position="test6"><Passwort>Internetsprachen</Passwort></Spamschutz></FeedbackDaten>

=== LukasVerwiebe/Internetsprachen-INS/Praktikum-INS/Webseite/08.01.2022_10_02_02.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FeedbackDaten SYSTEM "test.dtd"><FeedbackDaten Datum="08.01.2022" Uhrzeit="10:02:02"><PersoenlicheDaten id="1" position="test"><Anrede>Herr</Anrede><Vorname>Max</Vorname><Nachname>Mustermann</Nachname><Alter>30</Alter><Telefonnummer>1234567890</Telefonnummer><Emailadresse>test@web.de</Emailadresse><Webseite>-</Webseite></PersoenlicheDaten><Checkboxen id="2" position="test2"><Mailbox>ausgewählt</Mailbox><Rueckfragen>zur Verfügung</Rueckfragen><erneuterBesuch>Ja</erneuterBesuch></Checkboxen><EntdecktDurch id="3" position="test3"><AufmerksamDurch>Suchmaschine</AufmerksamDurch></EntdecktDurch><Noten id="4" position="test4"><NoteInhalt>2</NoteInhalt><NoteAussehen>2</NoteAussehen></Noten><Verbesserung id="5" position="test5"><Vorschlag>Dies ist ein Test</Vorschlag></Verbesserung><Spamschutz id="6" position="test6"><Passwort>Internetsprachen</Passwort></Spamschutz></FeedbackDaten>

=== LukasVerwiebe/Internetsprachen-INS/Praktikum-INS/Java-Programm/xml/Alte_Dateien/02.01.2022_12_13_15.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FeedbackDaten SYSTEM "test.dtd"><FeedbackDaten Datum="02.01.2022" Uhrzeit="12:13:15"><PersoenlicheDaten id="1" position="test"><Anrede>Herr</Anrede><Vorname>dfgh</Vorname><Nachname>gfhjx</Nachname><Alter>21</Alter><Telefonnummer>3465</Telefonnummer><Emailadresse>test@web.de</Emailadresse><Webseite>tedzWebseite</Webseite></PersoenlicheDaten><Checkboxen id="2" position="test2"><Mailbox>ausgewählt</Mailbox><Rueckfragen>zur Verfügung</Rueckfragen><erneuterBesuch>Ja</erneuterBesuch></Checkboxen><EntdecktDurch id="3" position="test3"><AufmerksamDurch>Linkliste</AufmerksamDurch></EntdecktDurch><Noten id="4" position="test4"><NoteInhalt>3</NoteInhalt><NoteAussehen>2</NoteAussehen></Noten><Verbesserung id="5" position="test5"><Vorschlag></Vorschlag></Verbesserung><Spamschutz id="6" position="test6"><Passwort>Internetsprachen</Passwort></Spamschutz></FeedbackDaten>

=== LukasVerwiebe/Internetsprachen-INS/Praktikum-INS/Webseite/04.01.2022_04_42_49.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FeedbackDaten SYSTEM "test.dtd"><FeedbackDaten Datum="04.01.2022" Uhrzeit="04:42:49"><PersoenlicheDaten id="1" position="test"><Anrede>Prof.</Anrede><Vorname>lukas</Vorname><Nachname>ver</Nachname><Alter>26</Alter><Telefonnummer>234456</Telefonnummer><Emailadresse>ayxxx@web.de</Emailadresse><Webseite>tedzWebseite</Webseite></PersoenlicheDaten><Checkboxen id="2" position="test2"><Mailbox>ausgewählt</Mailbox><Rueckfragen>zur Verfügung</Rueckfragen><erneuterBesuch>Ja</erneuterBesuch></Checkboxen><EntdecktDurch id="3" position="test3"><AufmerksamDurch>Freunde/Bekannte</AufmerksamDurch></EntdecktDurch><Noten id="4" position="test4"><NoteInhalt>5</NoteInhalt><NoteAussehen>4</NoteAussehen></Noten><Verbesserung id="5" position="test5"><Vorschlag>HAllo Test 1234.</Vorschlag></Verbesserung><Spamschutz id="6" position="test6"><Passwort>Internetsprachen</Passwort></Spamschutz></FeedbackDaten>
